services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: meal-planner-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    networks:
      backend_network:
        ipv4_address: 172.31.200.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
      network: host
    env_file:
      - .env
    container_name: meal-planner-backend
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      INSTANCE_NAME: meal-planner-db
      PROJECT_ID: ${PROJECT_ID}
      DRIVER_NAME: ${DRIVER_NAME}
    ports:
      - "${BACKEND_PORT}:8010"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      backend_network:
        ipv4_address: 172.31.200.20
      app_network:
        ipv4_address: 172.31.201.20

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        VITE_APP_API_BASE_URL: ${API_BASE_URL:-/api}
      network: host
    env_file:
      - .env
    container_name: meal-planner-frontend
    environment:
      VITE_APP_BACKEND_HOST: 172.31.201.20
      VITE_APP_BACKEND_PORT: 8010
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 172.31.201.10

volumes:
  mealplanner_db_data:
    driver: local

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.200.0/24
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.201.0/24
