services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: meal-planner-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - mealplanner_backend_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
      network: host
    env_file:
      - .env
    container_name: meal-planner-backend
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      INSTANCE_NAME: meal-planner-db
      PROJECT_ID: ${PROJECT_ID}
      DRIVER_NAME: ${DRIVER_NAME}
    ports:
      - "${BACKEND_PORT}:8010"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mealplanner_backend_network
      - mealplanner_app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
      network: host
    env_file:
      - .env
    container_name: meal-planner-frontend
    environment:
      REACT_APP_BACKEND_BASE_URL: http://backend:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mealplanner_app_network

volumes:
  mealplanner_db_data:

networks:
  mealplanner_backend_network:
    driver: bridge
  mealplanner_app_network:
    driver: bridge
